FROM php:8.2-apache

# Install dependencies
RUN apt-get update && apt-get install -y \
    libssl-dev \
    pkg-config \
    zip \
    unzip \
    && rm -rf /var/lib/apt/lists/*
RUN pecl install mongodb && docker-php-ext-enable mongodb
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html
COPY . /var/www/html/
RUN echo "DirectoryIndex form.php index.php index.html" > /etc/apache2/conf-available/site-settings.conf \
    && a2enconf site-settings
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html
RUN composer require mongodb/mongodb --no-interaction