FROM php:8.2-apache
RUN apt-get update && apt-get install -y libssl-dev pkg-config zip unzip
RUN pecl install mongodb
RUN docker-php-ext-enable mongodb
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY . /var/www/html/
RUN composer require mongodb/mongodb --working-dir=/var/www/html --no-interaction