FROM php:8.2-apache
RUN docker-php-ext-install pdo pdo_mysql
WORKDIR /var/www/html
COPY . /var/www/html/

RUN echo "DirectoryIndex form.php index.php index.html" > /etc/apache2/conf-available/my-index.conf \
&& a2enconf my-index
RUN chown -R www-data:www-data /var/www/html \
&& chmod -R 755 /var/www/html