services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file: .env
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    env_file: .env

volumes:
  db_data: